### ISSUE TITLE
May I ask about the path 'network_surgery' and the function "insert_conv_layers" ?

### ISSUE THREAD

**Issue by MubarkLa** [feichtenhofer/twostreamfusion#1]
Hello! I am doing the reproducing experiment on your code and I met  problems.

-----------------------------------------------------------------------------------------------------
In cnn_ucf101_fusion.m:

addpath('network_surgery');   %% line 20
[ netB ] = insert_conv_layers( netB, fusionLayerB(end), 'initMethod', opts.initMethod ); %% line 160

------------------------------------------------------------------------------------------------------

However, I cannot find the path 'network_surgery' and the function "insert_conv_layers" in your folder. May ask if I missed something?

Thank you very much.

**Comment by feichtenhofer** [comment]
Thanks for mentioning this, the file has been added.
