### ISSUE TITLE
The dataset links are down!

### ISSUE THREAD

**Issue by CooperLi** [feichtenhofer/twostreamfusion#13]
The links are invalid for download the datasets and models.
Could you please renew the link you offered so we could download the **datasets** and **models** for study?
Thanks a lot!

The invalid links ↓
![See](https://ooo.0o0.ooo/2016/09/28/57ebd1b46fba7.png)

**Comment by feichtenhofer** [comment]
Hi,
The links are working for me. Please check again.

**Comment by CooperLi** [comment]
Maybe I am in China...
I can open these link now via VPN.
Thanks anyway!

**Comment by abursuc** [comment]
It's a bit weird that the vpn was banned. Did you try a different web browser?

**Comment by CooperLi** [comment]
Yes, and now the links are accessible.
Thank you!
