### ISSUE TITLE
Can I get the 92.5% accuracy by directly run your code?

### ISSUE THREAD

**Issue by MubarkLa** [feichtenhofer/twostreamfusion#18]
Hello. 
I downloaded your code for the paper 'Two-Stream Convolutional Networks for Action Recognition in Videos', and run it directly. I tried many times but I can only get a result of 91.5%. 
Should I change somewhere in your code to get the  92.5% in your paper?

**Comment by feichtenhofer** [comment]
Hi,
In the paper a different testing strategy is employed.  "For testing we average
20 temporal predictions from each network by densely sampling the input-frame-stacks and their horizontal flips". Consider changing the opts.train.numValFrames variable.

**Comment by MubarkLa** [comment]
OK! Understand!
Thank you very very much.

**Comment by lvyali** [comment]
@MubarkLa 
Sorry to bother you,but can you tell me how to test this code to get the accuray?
