### ISSUE TITLE
for latest MatConvNet

### ISSUE THREAD

**Issue by mrxue1993** [feichtenhofer/twostreamfusion#2]
Hi, is your code support latest official MatConvNet?

**Comment by mrxue1993** [comment]
I am not able to compile your MatConvNet, but I can compile the official one, and the system I am using is Ubuntu14.04

**Comment by feichtenhofer** [comment]
Could you please give me more details on your problem?

**Comment by mrxue1993** [comment]
I use the command 

vl_compilenn('enableGpu', true, ...
'cudaRoot', '/usr/local/cuda-7.5', ...
'cudaMethod', 'nvcc')

to compile the official MatConvNet, it works fine. But with your MatConvNet, it will report error

Error using mex
/usr/bin/ld: /home/jia/Downloads/twostreamfusion-master/matconvnet/matlab/mex/.build/vl_nnconv.o: relocation
R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/jia/Downloads/twostreamfusion-master/matconvnet/matlab/mex/.build/vl_nnconv.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status


Error in vl_compilenn>mex_link (line 521)
mex(mopts{:}) ;

Error in vl_compilenn (line 473)
  mex_link(opts, objs, mex_dir, flags.link) ;

**Comment by mrxue1993** [comment]
I made some adjustment of the vl_compilenn.m file, copied the latest vl_compilenn.m into yours, add corresponding files into your MatConvNet, it compiles now. I will run the code to test whether further problem with this compile method

**Comment by LiangXu123** [comment]
i have the same problem,when i use parameter 'nvcc'_,it worked,but when i use ‘mex’,it collapse，but i got another way to fix it，just like yours，i copy the latest version vl_compilenn.m，it goes fine.
but my problem is when i run cnn_ucf101_spatial.m and cnn_ucf101_tempoal.m ,i got a new problem which hint of MATLAB is No public field dilate exists for class dagnn.Conv，in cnn_ucf101_tempoal（line 114）net=dagnn.DagNN.loadobj(net).do you hace the same problem or  do you know how to fix it ?

**Comment by L-CY** [comment]
@cc786537662  I encounter the same issue:
Error using vl_nnconv  Unknown option 'dilate'.
Have u solved this?
I use ubuntu14.04 cuda8.0 titan x pascal.

**Comment by LiangXu123** [comment]
@L-CY no ,i did't solve the problem
