### ISSUE TITLE
Using multiple GPUs to train the model error

### ISSUE THREAD

**Issue by kaisenseics** [feichtenhofer/twostreamfusion#28]
I am trying to use multiple GPUs to train the model. So I changed the default value of opts.train.gpus in the cnn_ucf101_fusion file from [1] to [1 2]. But it reports the following error:

line 503 int cnn_train_dag (this is the line that call fwrite)
the file id  is invalid. Please create a valid file id.

Could you please give some instruction on how to fix it? Thanks!

**Comment by feichtenhofer** [comment]
For multi-gpu training you will need to create a ramdisk where gradients are cached. Please first create a ramdisk and then set the path here: https://github.com/feichtenhofer/twostreamfusion/blob/master/cnn_ucf101_fusion.m#L47
