### ISSUE TITLE
cannot find 'models\ucf101-img-vgg16-split1-dr0.85.mat'

### ISSUE THREAD

**Issue by laura-wang** [feichtenhofer/twostreamfusion#29]
I follow the setup procedure and  download the data and model. But when I run cnn_ucf101_fusion(), it occurs one problem "unable to read file 'models\ucf101-img-vgg16-split1-dr0.85.mat'. No such file or directory". And I check the pretrained models document below, there is no such file. Could you please tell me where I can get this file? And also later the  'models\ucf101-TVL1flow-vgg16-split1-dr0.9.mat'.
Thanks!

**Comment by JasmineeYang** [comment]
@laura-wang Hello,I have the questions just like you.have you solved them out?

**Comment by jaisanliang** [comment]
I simply changed lines 56 and 57 to
```
opts.modelA = fullfile(opts.modelPath, [opts.dataSet '-img-vgg16-split' num2str(opts.nSplit) '.mat']) ;
opts.modelB = fullfile(opts.modelPath, [opts.dataSet '-TVL1flow-vgg16-split' num2str(opts.nSplit) '.mat']) ;
```
and that resolved the problem for me.
