### ISSUE TITLE
not able to open your data

### ISSUE THREAD

**Issue by mrxue1993** [feichtenhofer/twostreamfusion#3]
do you mind double check you Pre-computed optical flow images and resized rgb frames for the UCF101 and HMDB51 datasets? I tried download and open your data twice, still not able to open it

**Comment by feichtenhofer** [comment]
Should be working now?

**Comment by mrxue1993** [comment]
not yet, it said "An error occurred while loading the archive"

**Comment by abursuc** [comment]
For me it's working as it is. Maybe the PR I did here helps?https://github.com/feichtenhofer/twostreamfusion/pull/6

**Comment by mrxue1993** [comment]
thanks for your reply, my problem is that after I download the optical flow and RGB zip files, I am not able to extract the zip file instead of opening data with his code

**Comment by abursuc** [comment]
If you're on unix/linux you can try in the terminal:
```
cat ucf101_tvl1_flow.zip* > ucf101_tvl1_flow.zip
unzip ucf101_tvl1_flow.zip
```

**Comment by MonsterPotato** [comment]
Reference to non-existent field 'numFetchThreads'.

Error in cnn_ucf101_fusion (line 349)

I am wondering where can I find the defination of 'opt.numFetchThreads'.
And how can I fix this problem

**Comment by abursuc** [comment]
There seems to be an inconsistency in the naming. Just replace __numFetchThreads__ with __numThreads__

**Comment by mrxue1993** [comment]
I realized my problem now, thanks

**Comment by MonsterPotato** [comment]
How much gpu memory do I need at least if I want to run your demo?
My gpu is a Nvidia GTX 970. It has 4G memory. Can I run your demo on it?
