### ISSUE TITLE
could not find function cnn_train_dag.m

### ISSUE THREAD

**Issue by jiandan42** [feichtenhofer/twostreamfusion#4]
When I run cnn_ucf101_fusion(), I got a warning "Warning: Could not find appropriate function on path loading function handle /home/nvidia/Dropbox/mybox/PhD/ActionRecognition/THUMOS14/action_devkits/cnn_train_dag.m>extractStats" when loading the pretrained models. I also got an error "Undefined function or variable 'cnn_train_dag'" when running the last sentence "[info] = cnn_train_dag(net, imdb, fn, opts.train) ;". It seems that there is a missing function "cnn_train_dag.m". I used the default function "cnn_train_dag.m" of matConvNet but it still didn't work. Could you update the function "cnn_train_dag.m" or tell me how to solve this error. Thanks a lot.

**Comment by feichtenhofer** [comment]
I've added that function - thanks!
